//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "137.0.19+g8a1c4ce+chromium-137.0.7151.121"
#define CEF_VERSION_MAJOR 137
#define CEF_VERSION_MINOR 0
#define CEF_VERSION_PATCH 19
#define CEF_COMMIT_NUMBER 3192
#define CEF_COMMIT_HASH "8a1c4ce7a1e35e0a0fa3bd1a3b3e358d1421505b"
// clang-format on

#endif // CefVersion
